### ISSUE TITLE
imgui.Text limited UTF-8 encoding support

### ISSUE THREAD

**Issue by KagiamamaHIna** [dextercd/Noita-Dear-ImGui#3]
If a UTF-8 character is encoded with more than two bytes, it will be displayed as a '?'.
example:
![example](https://github.com/dextercd/Noita-Dear-ImGui/assets/128758465/e27ac7df-b9eb-4125-ab3b-0d5485210cbd)
```
local imgui = load_imgui({ version = "1.20.0", mod = "example" })

print("2 byte char, size:", string.len("б"))
print("2 byte char, size:", string.len("ш"))
print("3 byte char, size:", string.len("中"))
print("3 byte char, size:", string.len("。"))
print("4 byte char, size:", string.len("𬬭"))
local frCount = 0
local input_text = "中 。"
function OnWorldPostUpdate()

    if imgui.Begin("Fonts") then
        local fonts = {
            { "Noita Pixel",      imgui.GetNoitaFont() },
            { "Noita Pixel x1.4", imgui.GetNoitaFont1_4x() },
            { "Noita Pixel x1.8", imgui.GetNoitaFont1_8x() },
            { "ImGui",            imgui.GetImGuiFont() },
            { "Monospace",        imgui.GetMonospaceFont() },
            { "Glyph",            imgui.GetGlyphFont() },
        }
        _, input_text = imgui.InputText("Text", input_text)
        if frCount == 60 then
            GamePrint(input_text)
            --If your language selection is Simplified Chinese(简体中文), then the game will print the correct string.
        end
        local font_text = "2 byte:б ш | 3 byte:中 。| 4 byte:𬬭"
        for _, f in ipairs(fonts) do
            imgui.Separator()
            imgui.Text(f[1] .. ":")

            imgui.PushFont(f[2])
            imgui.Text(font_text)
            imgui.PopFont()
        end

        imgui.End()
    end
    if frCount == 60 then
        frCount = 0
    end
    frCount = frCount + 1
end
```

**Comment by KagiamamaHIna** [comment]
I think an API can be provided for custom font loading, which would solve the issue.
--https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-display-and-input-non-latin-characters-such-as-chinese-japanese-korean-cyrillic

**Comment by KagiamamaHIna** [comment]
I think an API can be provided for custom font loading, which would solve the issue.
--https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-display-and-input-non-latin-characters-such-as-chinese-japanese-korean-cyrillic

**Comment by dextercd** [comment]
Hey @KagiamamaHIna,

Thanks for letting me know about this. The issue isn't the utf-8 handling but the fact that none of the included fonts support these characters.

Adding font loading to the API would be a possible fix, but I don't really like the idea of mods providing their own fonts. Font loading is quite complicated, so exposing an API for it would be difficult. Mods loading fonts could also cause issues because GPU memory is a limited resource. I prefer keeping responsibility over this to the imgui mod.

I've pushed a new version of the imgui mod that includes the Noto Sans font for Asian languages. In the mod settings, you can make this the default font and choose between 3 variants, Japanese, Korean and Chinese (Simplified). https://github.com/dextercd/Noita-Dear-ImGui/releases

![image](https://github.com/dextercd/Noita-Dear-ImGui/assets/14349965/41c21f78-e146-4c8c-aa07-090a68fe2d5f)

Mods can also switch to the font like this:
```lua
imgui.PushFont(imgui.GetNotoFont())
imgui.Text(my_text)
imgui.PopFont()
```

Only one variant of the Noto Sans font can be loaded at a time and it can only be selected by the user. I hope that isn't too limiting.

Please let me know if this fixes the issue for you. :)
